INSERT INTO producto (id, nombre, descripcion, precio, oferta) VALUES 
(1, 'Espada larga', 'Hoja afilada de acero templado, ideal para combate cuerpo a cuerpo', 120.50, 1),
(2, 'Ballesta', 'Arma de proyectiles de largo alcance con gran precisión', 95.00, 0),
(3, 'Maza de guerra', 'Maza pesada con púas, diseñada para aplastar armaduras', 75.75, 1),
(4, 'Arco largo', 'Arco de madera flexible con gran potencia de tiro', 85.20, 0),
(5, 'Daga sigilosa', 'Cuchillo pequeño y ligero, ideal para ataques rápidos', 45.80, 1),
(6, 'Lanza de caballería', 'Lanza larga utilizada en cargas de caballería', 110.10, 0),
(7, 'Hacha de batalla', 'Hacha de doble filo para cortes devastadores', 90.50, 1),
(8, 'Mangual', 'Arma con cadena y bola con púas, difícil de bloquear', 78.90, 0),
(9, 'Mandoble', 'Espada de dos manos con gran poder de corte', 130.60, 1),
(10, 'Escudo de acero', 'Escudo resistente que protege contra golpes y flechas', 70.25, 0),
(11, 'Martillo de guerra', 'Martillo pesado diseñado para romper armaduras', 105.45, 1),
(12, 'Alabarda', 'Arma de asta con hoja y punta afilada, versátil en combate', 99.20, 0),
(13, 'Ballesta pesada', 'Variante más potente de la ballesta estándar', 140.80, 1),
(14, 'Estoque', 'Espada ligera y flexible, usada en duelos', 89.99, 0),
(15, 'Lanza corta', 'Arma de asta más manejable en combates cerrados', 55.50, 1),
(16, 'Mangual doble', 'Versión mejorada del mangual con doble bola de púas', 120.75, 0),
(17, 'Espada bastarda', 'Espada versátil de una mano y media', 125.90, 1),
(18, 'Daga envenenada', 'Daga con filo impregnado de veneno mortal', 65.20, 0),
(19, 'Hacha vikinga', 'Hacha ligera y rápida usada por los guerreros nórdicos', 98.30, 1),
(20, 'Lanza de guerra', 'Lanza reforzada para combate en campo abierto', 80.80, 0);